spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/mall?useUnicode=true&characterEncoding=UTF-8
      username: root
      password:
      driver-class-name: com.mysql.jdbc.Driver


####打印MyBatias日志
#logging:
#  level:
#    ### 开发环境使用DEBUG 生产环境info或者error
#    com.yehongzhi.strategy.dao: ERROR
