server:
  port: 8081

spring:
  profiles:
    active: dev
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

logging:
  level:
    com.yehongzhi.strategy.dao: info

mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: io.github.yehongzhi.model
