server:
  port: 8081

spring:
  profiles:
    active: dev

logging:
  level:
    com.yehongzhi.strategy.dao: info

mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: io.github.yehongzhi.model
